_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
always_save_checkpoint:
    value: true
backend:
    value: nccl
batch_size:
    value: 32
beta1:
    value: 0.9
beta2:
    value: 0.999
bias:
    value: false
block_size:
    value: 512
compile:
    value: false
dataset:
    value: customer_service
decay_lr:
    value: true
device:
    value: cuda
dropout:
    value: 0.2
dtype:
    value: bfloat16
eval_interval:
    value: 50
eval_iters:
    value: 20
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: gpt2
learning_rate:
    value: 2e-05
log_interval:
    value: 10
lr_decay_iters:
    value: 800
max_iters:
    value: 1000
min_lr:
    value: 2e-06
n_embd:
    value: 768
n_head:
    value: 12
n_layer:
    value: 12
out_dir:
    value: out-sentiment-ft
wandb_log:
    value: true
wandb_project:
    value: sentiment-analysis
wandb_run_name:
    value: gpt-sentiment-finetuned
warmup_iters:
    value: 100
weight_decay:
    value: 0.1
